### ISSUE TITLE
能否增加浏览器类型判断，手机，微信，平板，还是电脑。

### ISSUE THREAD

**Issue by indiboy** [apanly/browser-detector#1]
多谢！~~

**Comment by indiboy** [comment]
老大不在吗！~~~

**Comment by apanly** [comment]
@indiboy 你好最近比较忙，所以可能无法做了。你说的这个还是比较简单的，
微信很容易判断的
手机 ，平板 这个其实不是那么容易完成的，因为手机，平板品牌太多了。可以搜索一些出来然后判断就可以了满足常见的就行了
其他的就是pc了

建议可以fork这个代码，然后自己修改下，非常抱歉

**Comment by apanly** [comment]
微信判断参考：http://www.54php.cn/default/9.html
